language: go

go:
  - 1.4.2

install:
  - go get github.com/tools/godep
  - godep go build

deploy:
  provider: scalingo
  app: gorille
  api-key:
    secure: f5sVn/mTZ3xC4jnpYasI/uBl/WB/zTbMUad5dCF0hnNgFMi1NS5zjFjxPztWmGi555qUJtbvXXoj5GZ9D+T8OKAaTlNgIR2Ez5sssa8ftTH1FNdVJXadl36LB4wMDuR7vXYuB1bSZmds1gB8reirQJ7TO08I4XNJ6j8WQ3aUwz3LCM1fCItItkU4BUYPq6j5pNeasJqUuCS0rgU00zZLPyy7n+OyTFYRpn3amLPRxmlhZDKPcRJb2yOCrYT1T8aMQNhixKUAFXTmPo1qVKOg2LBtBoqpiRuzJVKaTOI40T51bX/kIO3+70FhMETHRbZRbrLdBDf/d/C5EggsgNGW2wDj/lTirEczIIqtkEwpIV/Jzf3tKsBzDH+dvaiagVVC6LmswrSGDyFdvm0uDmOQSZxsJe9mJmkHQvmIBdaHSvZ0b+1VIaJdNLbF3MnK0iX/b66avk1pl9b/SINXRliJ2lZCJhq+GEPZw1ujRRDA5dQz8/V4IwJnYPTkKOv/cW0TYyjl02alRRfi4mzELqkkay+3mXeDvsKHxstSIaCSguDrjQzgSqAKkCJKrL6sH5aJXIHQW8poDg4yyGN9NJ4dfvycOPvAgmw06pYRs7ei0EyuAMZa30hI1Eo4hsvc7EbbJucHZsiKwYuLEh4rwAoKE47pUiUKVt+9geFWm96OVWc=
  edge:
    source: Zyko0/dpl
    branch: master
  on:
    all_branches: true
